### ISSUE TITLE
Display of logging entries not possible

### ISSUE THREAD

**Issue by ma8bi4ne** [pagemachine/typo3-formlog#133] opened 2022-02-15 20:20 UTC
When trying to check the logged entries, I get the following error:

`Oops, an error occurred!
The type of property Pagemachine\Formlog\Domain\Model\FormLogEntry::page could not be identified, therefore the desired value (NULL) cannot be mapped onto it. The type of a class property is usually defined via php doc blocks. Make sure the property has a valid @var tag set which defines the type. `

Am using T3 v10.23. In the table tx_formlog_entries the data seems to be stored correctly.
Any hints?

**Comment by mbrodala** [comment] 2022-02-16 07:44
Sounds like a duplicate of #132, please add as much debugging info and a way to reproduce it in that ticket.

**Closed by mbrodala** 2022-02-16 07:44 UTC
Labels: duplicate
